report_interval: 50
batch_log: False
prefix_for_plot_names: ""

data_loaders:
  test:
    split_key: test_idxs
    is_graph: True
    drop_last: True 

    pin_memory: False
    seed: null
    num_workers: 0
    batch_size: 2
