master_port: 12356 # 12355 initial value
gpu_list: [] 

kind: gnn
launch_wandb: True

defaults:
    - data/dataset/debug@data.dataset: debug_graph_classification_X_hits_t_Y_eventType
    - data/transforms/debug@data.transforms: debug_norm_X_hits_time_Y_none

    # Order matters
    - tasks/train: debug_graph_cpu
    - tasks/restore_best_state: debug_restore_best_state
    - tasks/evaluate: debug_graph


    - sampler@tasks.train.data_loaders.train.sampler_config: subset_random
    - sampler@tasks.train.data_loaders.validation.sampler_config: subset_sequential   
    - sampler@tasks.evaluate.data_loaders.test.sampler_config: subset_sequential

    - model: debug_resgated_classification_4in_2out
    - engine: debug_gnn_classifier
    - loss@tasks.train.loss: cross_entropy
    - optimizers@tasks.train.optimizers: adam

    - wandb/debug@wandb: debug_wandb

    
    - _self_