master_port: 12356 # 12355 initial value
gpu_list: [] 

kind: gnn
launch_wandb: True

defaults:
    - data/dataset: debug_graph_regression_X_t_c_Y_energie_Ed_hits
    - data/transforms: debug_norm_X_t_c_Y_energy

    - tasks/train: debug_graph_cpu
    - tasks/restore_best_state: debug_restore_best_state
    - tasks/evaluate: debug_graph

    - sampler@tasks.train.data_loaders.train.sampler_config: subset_random
    - sampler@tasks.train.data_loaders.validation.sampler_config: subset_sequential   
    - sampler@tasks.evaluate.data_loaders.test.sampler_config: subset_sequential

    - model: debug_resgated_regression_2in_1out
    - engine: debug_gnn_regresser
    - loss@tasks.train.loss: mse
    - optimizers@tasks.train.optimizers: adam
    - wandb: debug_wandb

    
    - _self_