master_port: 12357 # 12355 initial value
gpu_list: [] 

kind: gnn
launch_wandb: True

defaults:

    # - model: resgated_1in_1out
    - model: resgated_1in_1out_meanpool
    # - model: gat_molecular_paper

    - engine: gnn_regresser
    # - wandb: wandb_config_regression_e-_energy_gat # Will not be taken in account if launch_wandb=False
    - wandb: wandb_config_regression_e-_energy_resgatedconv 


    - data/dataset/benprod@data.dataset: data_dataset_e-_50k_target_energy_train_q_edges_txyz
    - data/transforms/regression@data.transforms: LogNorm_q_Norm_energy_e-

    # Order of tasks matters
    - tasks/restore_state: restore_state

    - tasks/evaluate: graph_no_batch_log_evaluate
    - loss@tasks.evaluate.loss: mse
    - sampler@tasks.evaluate.data_loaders.test.sampler_config: subset_sequential
    
    - _self_